variables:
   GCP_ACCOUNT: #service account
   GCP_KEY: #service account JSON key
   GCP_PROJECT_ID: #GCP progect id
   GCP_REPOSITORY: #ARTIFACT REGISTRY repository name
   GCP_HOSTNAME: #ARTIFACT REGISTRY hosename
   
   
stages:
  - build
  - push

build-image:
  stage: build
  tags:
    - docker-build
  script:
    - docker build -t img.greattree.com.tw/${CI_PROJECT_NAME}   .
    - docker push img.greattree.com.tw/${CI_PROJECT_NAME}
  only:
    - master

push-image:
  image: google/cloud-sdk
  stage: push
  tags:
    - docker-build
  script:
    - echo "${GCP_KEY}" >> /tmp/gcpkey.json
    - gcloud auth activate-service-account ${GCP_ACCOUNT} --key-file=/tmp/gcpkey.json
    - gcloud auth configure-docker ${GCP_HOSTNAME} -q
    - docker tag img.greattree.com.tw/${CI_PROJECT_NAME} ${GCP_HOSTNAME}/${GCP_PROJECT_ID}/${GCP_REPOSITORY}/${CI_PROJECT_NAME}
    - docker push ${GCP_HOSTNAME}/${GCP_PROJECT_ID}/si-docker/${CI_PROJECT_NAME}
    - docker rmi img.greattree.com.tw/${CI_PROJECT_NAME}
    - docker rmi ${HOSTNAME}-docker.pkg.dev/${GCP_PROJECT_ID}/${GCP_REPOSITORY}/${CI_PROJECT_NAME}
  only:
    - master