version: '3.1'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www/:/www/:rw
      - ./ssl:/ssl
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php1
    restart: always
  php1:
    build: ./
    ports:
      - "9000:9000"
    volumes:
      - ./www/:/www/:rw
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
    restart: always
    cap_add:
      - SYS_PTRACE