version: '3.1'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./www/:/www/:rw
      - ./ssl:/ssl
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php1
    restart: always
  php1:
    build: ./
    volumes:
      - ./www/:/www/:rw
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
    restart: always
    links:
      - mysql
    cap_add:
      - SYS_PTRACE
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata: