version: '3.1'
services:
  nginx:
    image: nginx
    volumes:
      - /mnt/nextcloud/www:/var/www/html:rw
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/ssl
    ports:
      - "80:80"
      - "443:443"
    links:
      - php1
      - collabora
    restart: always
  php1:
    image: nextcloud:fpm-alpine
    volumes:
      - /mnt/nextcloud/www:/var/www/html:rw
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_HOST: mysql
    links:
      - mysql
  collabora:
    image: collabora/code
    restart: always
    privileged: true
    environment:
      - "username=admin"
      - "password=admin"
      - "domain=cloud.lexnovia.com"
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - /mnt/nextcloud/mysql:/var/lib/mysql
